version: '3.4'

networks:
  dev-network:
    driver: bridge

services:
  gerenciador_contatos_clientes_back:
    depends_on:
      - "postgres16"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ASPNETCORE_HTTPS_PORTS=7001
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=admin;Host=postgres16;Port=5432;Database=gerenciador-contatos; Integrated Security=true;Pooling=true;
    ports:
      - "5001:5001"
      - "7001:7001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - dev-network

  blazorapp:
    depends_on:
        - gerenciador_contatos_clientes_back
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:7000;http://+:5000
        - BACKEND_URL=https://gerenciador_contatos_clientes_back:7001
    ports:
        - "5000:5000"
        - "7000:7000"
    networks:
          - dev-network

  postgres16:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gerenciador-contatos
    ports:
      - "5432:5432"
    volumes:
      - ${APPDATA}/PostgreSQL:/var/lib/postgresql/data
    networks:
      - dev-network

volumes:
    app_data:
