CREATE DATABASE "gerenciador-contatos";

CREATE TABLE public.clientes (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome varchar(100) NOT NULL,
	cnpj varchar(14) NOT NULL,
	datafundacao date NOT NULL,
	ativo boolean DEFAULT true NOT NULL,
	CONSTRAINT clientes_pk PRIMARY KEY (id),
	CONSTRAINT clientes_unique_cnpj UNIQUE (cnpj)
);

CREATE TABLE public.contatos (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	clienteid int NOT NULL,
	nome varchar(100) NOT NULL,
	email varchar(100) NOT NULL,
	telefone varchar(100) NULL,
	cargo varchar(50) NULL,
	CONSTRAINT contatos_pk PRIMARY KEY (id),
	CONSTRAINT contatos_clientes_fk FOREIGN KEY (clienteid) REFERENCES public.clientes(id)
);
